# Generated by Django 5.1.6 on 2025-03-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_transcriber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='audio_file',
            new_name='media_file',
        ),
    ]
